// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA8h1oWRN4td69oJNfdzCseDUkQ2IxT_8',
    appId: '1:890074561400:web:3060aed5f6d40c0dea268d',
    messagingSenderId: '890074561400',
    projectId: 'avepus-gettogether',
    authDomain: 'avepus-gettogether.firebaseapp.com',
    storageBucket: 'avepus-gettogether.appspot.com',
    measurementId: 'G-MYVS7B8QJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9wifhn-Iom7itqnaJUozXZgpr0dQrmnc',
    appId: '1:890074561400:android:cc786bfaf1ab2738ea268d',
    messagingSenderId: '890074561400',
    projectId: 'avepus-gettogether',
    storageBucket: 'avepus-gettogether.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5g_pTosom64mhAXotaBx8c0E-IaMmDto',
    appId: '1:890074561400:ios:1e95663b9ada74b0ea268d',
    messagingSenderId: '890074561400',
    projectId: 'avepus-gettogether',
    storageBucket: 'avepus-gettogether.appspot.com',
    iosBundleId: 'com.example.getTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5g_pTosom64mhAXotaBx8c0E-IaMmDto',
    appId: '1:890074561400:ios:0d9587fef043920dea268d',
    messagingSenderId: '890074561400',
    projectId: 'avepus-gettogether',
    storageBucket: 'avepus-gettogether.appspot.com',
    iosBundleId: 'com.example.getTogether.RunnerTests',
  );
}
