// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4Q9rzICUtz9qhGLmEp9DCem2i-VitlM',
    appId: '1:769257794479:web:0ec1127e9fa4a4dbe3dd5a',
    messagingSenderId: '769257794479',
    projectId: 'avepus-get-together',
    authDomain: 'avepus-get-together.firebaseapp.com',
    storageBucket: 'avepus-get-together.appspot.com',
    measurementId: 'G-8V3Z6XHRP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ftRuCQqARtMgI-8q7j18dPMxkM0jvQE',
    appId: '1:769257794479:android:12ea0f270e230a27e3dd5a',
    messagingSenderId: '769257794479',
    projectId: 'avepus-get-together',
    storageBucket: 'avepus-get-together.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArQKIiW779_kOpnXyRulyH9w07az199vc',
    appId: '1:769257794479:ios:845c4e5f706311e8e3dd5a',
    messagingSenderId: '769257794479',
    projectId: 'avepus-get-together',
    storageBucket: 'avepus-get-together.appspot.com',
    iosBundleId: 'com.example.getTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArQKIiW779_kOpnXyRulyH9w07az199vc',
    appId: '1:769257794479:ios:976750f388f2f935e3dd5a',
    messagingSenderId: '769257794479',
    projectId: 'avepus-get-together',
    storageBucket: 'avepus-get-together.appspot.com',
    iosBundleId: 'com.example.getTogether.RunnerTests',
  );
}
